# Generated by Django 5.2.1 on 2025-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.AddField(
            model_name='termin',
            name='tags',
            field=models.ManyToManyField(to='terms.tag'),
        ),
    ]
