# Generated by Django 5.2.1 on 2025-05-28 09:50

from django.db import migrations

def save_db(apps, schema_editor):
    Tag = apps.get_model("tags", "Tag")
    Termin = apps.get_model("terms", "Termin")


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_termin_tags'),
    ]

    operations = [
        # migration.RunPython()
    ]
